version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - database

  database:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=1067d36d6f7cecba13e811f5f1267879af32af0c52f3b85dce4e8c98d4b81eaa
      - POSTGRES_USER=lyxnoousoafoep
      - POSTGRES_DB=d9sb6ii6e86fl2