# Generated by Django 4.0.5 on 2022-06-03 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_year', models.IntegerField(default=0)),
                ('acquired', models.BooleanField()),
                ('thumbnail', models.TextField(max_length=2048)),
                ('year', models.SmallIntegerField()),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
