# Generated by Django 4.0.5 on 2022-06-24 10:02

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', shortuuidfield.fields.ShortUUIDField(blank=True, default=None, editable=False, max_length=22, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('published_year', models.SmallIntegerField(default=0)),
                ('acquired', models.BooleanField(default=False)),
                ('thumbnail', models.TextField(blank=True, default=None, max_length=2048, null=True)),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
