# Generated by Django 4.0.5 on 2022-06-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
