# Generated by Django 4.0.5 on 2022-06-04 09:31

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
