# Generated by Django 4.0.5 on 2022-06-03 17:00

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_year_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
