# Generated by Django 4.0.5 on 2022-06-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_year_alter_author_name'),
    ]
