# Generated by Django 4.0.5 on 2022-06-04 08:49

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
