# Generated by Django 4.0.5 on 2022-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_year'),
    ]

    operations = [

        migrations.AlterField(
            model_name='book',
            name='acquired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.TextField(default='', max_length=2048),
        ),
    ]
