# Generated by Django 4.0.5 on 2022-06-17 10:29

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_year_alter_book_acquired_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, default=None, editable=False, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.TextField(
                blank=True, default=None, max_length=2048, null=True),
        ),
    ]
