# Generated by Django 4.0.5 on 2022-06-04 09:04

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='some_id',
            field=models.CharField(default=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22), max_length=10),
        ),
    ]
