# Generated by Django 4.0.5 on 2022-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_id1',
            field=models.UUIDField(default='AAt8CPFzKCRTtmdCRzUssv', editable=False),
        ),
    ]
