# Generated by Django 4.0.5 on 2022-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_external_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id1',
            field=models.UUIDField(default='kas6hLKcnyqxMdxAmwsgPb', editable=False),
        ),
    ]
