# Generated by Django 4.0.5 on 2022-06-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_external_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='external_id1',
        ),
    ]
